version: "3.2"

services:
  database:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
    ports:
      - "${DB_PORT_EXPOSE}:5432"

  app:
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8099:8000"
    depends_on:
      - database
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s

networks:
  cc:
    driver: bridge