"""added constraint

Revision ID: 4e5284bca1c4
Revises: d7d20558f2e9
Create Date: 2023-04-06 16:04:01.011686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e5284bca1c4'
down_revision = 'd7d20558f2e9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('cur_pair_date', 'rates', ['from_cur', 'to_cur', 'date'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cur_pair_date', 'rates', type_='unique')
    # ### end Alembic commands ###
